### ISSUE TITLE
MacOSX additional field host_ip calculation failed

### ISSUE THREAD

**Issue by gghez** [cmanaha/python-elasticsearch-logger#28] opened 2017-07-19 20:54 UTC
This code `socket.gethostbyname(socket.gethostname())` is currently failing on Darwin (`import platform: platform.system()` to detect this platform).
https://github.com/cmanaha/python-elasticsearch-logger/blob/master/cmreslogging/handlers.py#L194

As a MacOSX user, I would like to be able to use your logging handler, but this simple instruction leads to nothing is working.

Do you think @cmanaha you could add such a check?

**Comment by cmanaha** [comment] 2017-07-19 22:26
That's a bit strange; I do develop and test on a Darwin platform and run final integration on Linux. If anything the only platform I'm not running consistently every new release is Windows. 

There could be an extra try/catch capture on the initialisation to bypass and not add those extra fields to the records when the call fails, however those fields are quite relevant to identify the producer of the logs. I'm not convinced the code should just swallow those relevant details and then keep processing; For production I'd rather prefer the code to fail to indicate there is something wrong with the setup and the producer of the logs cannot be identified.

Additionally the fact that your python installation fails on the underlying syscalls for  socket.gethostbyname(socket.gethostname()) call may potentially indicate something more related with your setup either on resolution or on the calls.

Would you mind to confirm what is the python interpreter version you use?
Also it may worth to run those two commands on a python interpreter and get more details of the error that you actually get before considering changing any code.

**Comment by cmanaha** [comment] 2017-10-08 21:02
Closing this issue; No feedback provided and cannot reproduce.

**Closed by cmanaha** 2017-10-08 21:02 UTC

**Comment by walkingpendulum** [comment] 2017-11-01 07:53
Get this error too on OS X Sierra. There is fix -- add to `/etc/hosts` line `127.0.0.1  yourhost`, where `yourhost` if what socket.gethostname() returns.
