### ISSUE TITLE
Log records get lost

### ISSUE THREAD

**Issue by hstadler** [cmanaha/python-elasticsearch-logger#13] opened 2017-03-01 13:05 UTC
Hi,

I face the problem that some log messages are not sent to Elasticsearch. The reason seems to be that the buffer is not thread safe because `flush` is called concurrently by the flush timer. As a result, when the flush timer calls `flush`, there is a good chance that log records that were appended to the buffer by `emit` in the meantime get lost.
Disabling the timer might solve the problem. But it has to be ensured that log messages from the elasticsearch library (which are generated during `flush`) are filtered, otherwise a _maximum recursion depth exceeded_ exception can occur.

**Comment by cmanaha** [comment] 2017-03-30 21:03
Disabling the timer will imply that people using the log appender for and rely on getting events/logs in es may have to wait until the buffer is full. I'd rather prefer to use locks and an aux queue.

Have you got any test case that reproduce the race condition that can be used to verify the issue goes away once this gets implemented?

**Comment by cmanaha** [comment] 2017-04-13 10:39
There is a new version with changes on the timer; May worth checking back again to see if you can reproduce. Otherwise I'll close this issue.

**Comment by KonstantinSchubert** [comment] 2017-04-13 20:57
I was seeing the same or a very similar problem. In my interpretation of what is going on, the process was forked after the __init__ method which caused the handler to be copied. However, the timer was still only acting on the original copy. This interpretation might be wrong however, since I am new to multiprocessing.

Anyways, my PR #17 fixed the problem for you and might also fix it in your case, even if it isn't the same one I was seeing. The PR is in the new version, which is probably what @hstadler is referring to.

**Comment by KonstantinSchubert** [comment] 2017-04-19 20:31
NVM, I had no idea that the timer was executing concurrently. 

I saw your pull request and I now agree that my change did NOT fix your issue. But your PR does. Sorry for the noise.

**Comment by hstadler** [comment] 2017-04-20 06:23
No problem, questions / feedback are welcome.
As noted by you, the timer is concurrent but within the same process context.

**Closed** 2017-07-10 13:07 UTC
