### ISSUE TITLE
flush() is not emptying the buffer if raise_on_indexing_exceptions is true

### ISSUE THREAD

**Issue by ajallooeian** [cmanaha/python-elasticsearch-logger#21] opened 2017-06-22 12:31 UTC
The last line of the function is:

self._buffer = []

Suggestion: maybe it should be:

finally:
    self._buffer = []

**Comment by cmanaha** [comment] 2017-06-22 19:10
Good point.  Will add it to the list to change as soon as I have some time.

**Comment by aldbr** [comment] 2017-07-10 14:08
The problem is fixed with the last update.

**Closed** 2017-07-10 14:09 UTC
